### ISSUE TITLE
muutus.txt

### ISSUE THREAD

**Issue by kuuba** [Andres1987/tudeng15-kodutood#1]
Sedasamust et, muutus.txt on jätkuvalt muutusteta. Ma sinna omalt poolt küll kirjutasin oma kommentaari aga näib et praegu asi lihtsalt seisab niisama. Nüüdsest võiksime üritada github-i issue-tracking süsteemi kasutada (no ikka sedasama, milles ma praegu kirjutan). Vaatame kui sujuvalt see siis käivitub ka.

**Comment by kuuba** [comment]
Ma siis kopeerisin alguseosa oma kommentaarist siia kah (ülesande teine pool puudutab ls tegemist suhtelise viite kaudu):

Aga proovi uuesti - kustuta .bashrc ja .bash_profile ära, vaata mis muutub ja
siis kopeeri tagasi - võid nad ka niisama ümber nimetada näiteks

Muidu, miks nende ülesannetega asi seisma on jäänud? Ega ma kuskilt otsast abistada ei saa?

**Comment by Andres1987** [comment]
Tegin natuke seda kodutood uusti. L6in uue muutus.txt faili

**Comment by kuuba** [comment]
Kas midagi on vahet eelmise failiga kah?
